version: '3.8'
services:
  frontend:
    image: qazer25/iot-frontend:${app_VERSION:-latest}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_HOST: fedoraapi.relentlessadmin.org 
    ports:
      - "3000:3000"
    labels:
      kompose.hpa.replicas.min: 2
      kompose.hpa.replicas.max: 5
