version: '3.8'
services:
  frontend:
    image: qazer25/iot-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3001:3000"

